export const LOGIN_ROUTE= '/login'
export const REGISTRATION_ROUTE= '/registration'
export const GAME_ROUTE= '/game'
export const TABLE_SCORE_ROUTE= '/score'

export const REGISTRATION ='REGISTRATION'
export const LOGIN = 'LOGIN'
export const UPDATE = 'UPDATE'
export const LOGOUT = 'LOGOUT'
export const TABLE = 'TABLE'